/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Von_Neumann;

/**
 *
 * @author Langas
 */
public class Neumann_Principal extends javax.swing.JFrame {

    /**
     * Creates new form Neumann_Principal
     */
    public Neumann_Principal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel_Neumann = new javax.swing.JPanel();
        jLabel_Dato2 = new javax.swing.JLabel();
        jLabel_Flecha18 = new javax.swing.JLabel();
        jLabel_Flecha9 = new javax.swing.JLabel();
        jLabel_FlechaAD = new javax.swing.JLabel();
        jLabel_Flecha4 = new javax.swing.JLabel();
        jLabel_Instruccion = new javax.swing.JLabel();
        jLabel_Dato1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel_Flecha8 = new javax.swing.JLabel();
        jLabel_DirM = new javax.swing.JLabel();
        jLabel_UC = new javax.swing.JLabel();
        jLabel_Flecha14 = new javax.swing.JLabel();
        jLabel_Bus = new javax.swing.JLabel();
        jLabel_Flecha13P = new javax.swing.JLabel();
        Flecha_Grande = new javax.swing.JLabel();
        jPanel_Memoria = new javax.swing.JPanel();
        jLabel_Decod = new javax.swing.JLabel();
        jLabel_CuadroDirec = new javax.swing.JLabel();
        jLabel_Linea1 = new javax.swing.JLabel();
        jLabel_Linea2 = new javax.swing.JLabel();
        jLabel_DM = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel_Unidad_Ejecucion = new javax.swing.JPanel();
        jLabel_ALU = new javax.swing.JLabel();
        jLabel_Registros = new javax.swing.JLabel();
        jLabel_RegistroE = new javax.swing.JLabel();
        jLabel_FlechaA = new javax.swing.JLabel();
        jLabel_FlechaArri = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jPanel_UnidadC = new javax.swing.JPanel();
        jLabel_CP = new javax.swing.JLabel();
        jLabel_RI = new javax.swing.JLabel();
        jLabelDecodi = new javax.swing.JLabel();
        jLabel_AGS = new javax.swing.JLabel();
        jLabel_AGS2 = new javax.swing.JLabel();
        jLabel_GS = new javax.swing.JLabel();
        jLabel_RsultadoB = new javax.swing.JLabel();
        jLabel_ARD = new javax.swing.JLabel();
        jLabel_Flecha11 = new javax.swing.JLabel();
        jLabel_DS = new javax.swing.JLabel();
        jLabel_TR = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel_Memoria = new javax.swing.JLabel();
        jLabel_LineaL = new javax.swing.JLabel();
        jLabel_AbajoD_UJ = new javax.swing.JLabel();
        jLabel_UnidadEje = new javax.swing.JLabel();
        jLabel_Cuadrado = new javax.swing.JLabel();
        jLabel_CPU = new javax.swing.JLabel();
        jLabel1_Flecha15 = new javax.swing.JLabel();
        jLabel_UnidadES = new javax.swing.JLabel();
        jLabel_DispositivosES = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel_Neumann.setBackground(new java.awt.Color(255, 255, 255));
        jPanel_Neumann.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel_Dato2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Dato.png"))); // NOI18N
        jPanel_Neumann.add(jLabel_Dato2, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 120, 50, 30));

        jLabel_Flecha18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Flecha 18_1.png"))); // NOI18N
        jPanel_Neumann.add(jLabel_Flecha18, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 130, 730, 100));

        jLabel_Flecha9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Flecha 9.png"))); // NOI18N
        jPanel_Neumann.add(jLabel_Flecha9, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 30, 1000, 280));

        jLabel_FlechaAD.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Flecha 5.png"))); // NOI18N
        jPanel_Neumann.add(jLabel_FlechaAD, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 580, 30, 160));

        jLabel_Flecha4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Flecha 3.png"))); // NOI18N
        jPanel_Neumann.add(jLabel_Flecha4, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 130, 260, 170));

        jLabel_Instruccion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Instruccion.png"))); // NOI18N
        jPanel_Neumann.add(jLabel_Instruccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 70, -1, -1));

        jLabel_Dato1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Dato.png"))); // NOI18N
        jPanel_Neumann.add(jLabel_Dato1, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 120, 50, 30));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/CPUUnidad de Procesamiento Central.png"))); // NOI18N
        jPanel_Neumann.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 670, 270, 70));

        jLabel_Flecha8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Flecha 8.png"))); // NOI18N
        jPanel_Neumann.add(jLabel_Flecha8, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 80, 840, 230));

        jLabel_DirM.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Dirección de Memoria.png"))); // NOI18N
        jPanel_Neumann.add(jLabel_DirM, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 10, 150, 30));

        jLabel_UC.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/UNIDAD DECONTROL.png"))); // NOI18N
        jPanel_Neumann.add(jLabel_UC, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 600, 120, 40));

        jLabel_Flecha14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Flecha 14.png"))); // NOI18N
        jPanel_Neumann.add(jLabel_Flecha14, new org.netbeans.lib.awtextra.AbsoluteConstraints(980, 380, 220, 390));

        jLabel_Bus.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/BUS DE DATOS EINSTRUCCIONES.png"))); // NOI18N
        jPanel_Neumann.add(jLabel_Bus, new org.netbeans.lib.awtextra.AbsoluteConstraints(1160, 30, 130, 40));

        jLabel_Flecha13P.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Flecha 13.png"))); // NOI18N
        jPanel_Neumann.add(jLabel_Flecha13P, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 540, 50, 200));

        Flecha_Grande.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Flecha Grande.png"))); // NOI18N
        jPanel_Neumann.add(Flecha_Grande, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 50, 1310, -1));

        jPanel_Memoria.setBackground(new java.awt.Color(0, 51, 51));
        jPanel_Memoria.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel_Decod.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Decodificardor de Direcciones.png"))); // NOI18N
        jPanel_Memoria.add(jLabel_Decod, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 80, 300));

        jLabel_CuadroDirec.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Cuadro de Memoria.png"))); // NOI18N
        jPanel_Memoria.add(jLabel_CuadroDirec, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 20, 139, 287));

        jLabel_Linea1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Línea 4.png"))); // NOI18N
        jPanel_Memoria.add(jLabel_Linea1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 280, 70, 10));

        jLabel_Linea2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Línea 4.png"))); // NOI18N
        jPanel_Memoria.add(jLabel_Linea2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 40, 70, 10));

        jLabel_DM.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_DM.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Dirección máxima._1.png"))); // NOI18N
        jPanel_Memoria.add(jLabel_DM, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 280, 60, 50));

        jLabel2.setBackground(new java.awt.Color(70, 70, 70));
        jLabel2.setFont(new java.awt.Font("Open Sans", 1, 13)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(112, 112, 112));
        jLabel2.setText("0");
        jPanel_Memoria.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 10, -1, -1));

        jPanel_Neumann.add(jPanel_Memoria, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 280, 370, 320));

        jPanel_Unidad_Ejecucion.setBackground(new java.awt.Color(0, 51, 51));
        jPanel_Unidad_Ejecucion.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel_ALU.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/ALU.png"))); // NOI18N
        jPanel_Unidad_Ejecucion.add(jLabel_ALU, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 160, 210, 80));

        jLabel_Registros.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Registros.png"))); // NOI18N
        jPanel_Unidad_Ejecucion.add(jLabel_Registros, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 40, 290, 70));

        jLabel_RegistroE.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Registro de Estatus.png"))); // NOI18N
        jPanel_Unidad_Ejecucion.add(jLabel_RegistroE, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 290, 210, 90));

        jLabel_FlechaA.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Fecha.png"))); // NOI18N
        jPanel_Unidad_Ejecucion.add(jLabel_FlechaA, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 100, 20, 70));

        jLabel_FlechaArri.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Fecha 2.png"))); // NOI18N
        jPanel_Unidad_Ejecucion.add(jLabel_FlechaArri, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 110, 20, 60));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Fecha.png"))); // NOI18N
        jPanel_Unidad_Ejecucion.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 230, 20, 60));

        jPanel_Neumann.add(jPanel_Unidad_Ejecucion, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 190, 350, 410));

        jPanel_UnidadC.setBackground(new java.awt.Color(0, 51, 51));
        jPanel_UnidadC.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel_CP.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Contador de Programa.png"))); // NOI18N
        jPanel_UnidadC.add(jLabel_CP, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 40, 150, 90));

        jLabel_RI.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Registro de Instrucciones.png"))); // NOI18N
        jPanel_UnidadC.add(jLabel_RI, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, 150, 90));

        jLabelDecodi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Decodificador.png"))); // NOI18N
        jPanel_UnidadC.add(jLabelDecodi, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, 150, 40));

        jLabel_AGS.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Fecha 12.png"))); // NOI18N
        jPanel_UnidadC.add(jLabel_AGS, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 190, 30, 40));

        jLabel_AGS2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Fecha 12.png"))); // NOI18N
        jPanel_UnidadC.add(jLabel_AGS2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 190, 30, 40));

        jLabel_GS.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Generador de Señales.png"))); // NOI18N
        jPanel_UnidadC.add(jLabel_GS, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 210, 150, 100));

        jLabel_RsultadoB.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Resultado y banderas delRegistro deEstatus.png"))); // NOI18N
        jPanel_UnidadC.add(jLabel_RsultadoB, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 200, 110, 90));

        jLabel_ARD.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Fecha 10.png"))); // NOI18N
        jPanel_UnidadC.add(jLabel_ARD, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 120, 20, 50));

        jLabel_Flecha11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Flecha 11.png"))); // NOI18N
        jPanel_UnidadC.add(jLabel_Flecha11, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 120, 180, 40));

        jLabel_DS.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Dirección (Salto).png"))); // NOI18N
        jPanel_UnidadC.add(jLabel_DS, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 160, 110, 20));

        jLabel_TR.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Trabajo a realizar.png"))); // NOI18N
        jPanel_UnidadC.add(jLabel_TR, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 320, 120, 30));

        jPanel_Neumann.add(jPanel_UnidadC, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 240, 360, 360));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Flecha 16.png"))); // NOI18N
        jPanel_Neumann.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(1260, 320, 60, 40));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Flecha 17.png"))); // NOI18N
        jPanel_Neumann.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1260, 380, 60, 40));

        jPanel1.setBackground(new java.awt.Color(0, 51, 51));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel_Neumann.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1210, 200, 60, 400));

        jLabel_Memoria.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/MEMORIA.png"))); // NOI18N
        jPanel_Neumann.add(jLabel_Memoria, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 600, 90, 30));

        jLabel_LineaL.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Flecha 6.png"))); // NOI18N
        jPanel_Neumann.add(jLabel_LineaL, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 730, 1030, 10));

        jLabel_AbajoD_UJ.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Flecha 7.png"))); // NOI18N
        jPanel_Neumann.add(jLabel_AbajoD_UJ, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 590, 20, 150));

        jLabel_UnidadEje.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/UNIDAD DEEJECUCION.png"))); // NOI18N
        jPanel_Neumann.add(jLabel_UnidadEje, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 600, 100, 40));

        jLabel_Cuadrado.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Cuadro.png"))); // NOI18N
        jPanel_Neumann.add(jLabel_Cuadrado, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 160, 810, 520));
        jPanel_Neumann.add(jLabel_CPU, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 680, 260, 50));

        jLabel1_Flecha15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Flecha 15.png"))); // NOI18N
        jPanel_Neumann.add(jLabel1_Flecha15, new org.netbeans.lib.awtextra.AbsoluteConstraints(1230, 600, 20, 130));

        jLabel_UnidadES.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/UNIDADE-S (I-O).png"))); // NOI18N
        jPanel_Neumann.add(jLabel_UnidadES, new org.netbeans.lib.awtextra.AbsoluteConstraints(1250, 600, 70, 60));

        jLabel_DispositivosES.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/DispositivosE-S.png"))); // NOI18N
        jPanel_Neumann.add(jLabel_DispositivosES, new org.netbeans.lib.awtextra.AbsoluteConstraints(1270, 350, 80, 50));

        getContentPane().add(jPanel_Neumann, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1366, 868));

        setSize(new java.awt.Dimension(1366, 829));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Neumann_Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Neumann_Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Neumann_Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Neumann_Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Neumann_Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Flecha_Grande;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel1_Flecha15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabelDecodi;
    private javax.swing.JLabel jLabel_AGS;
    private javax.swing.JLabel jLabel_AGS2;
    private javax.swing.JLabel jLabel_ALU;
    private javax.swing.JLabel jLabel_ARD;
    private javax.swing.JLabel jLabel_AbajoD_UJ;
    private javax.swing.JLabel jLabel_Bus;
    private javax.swing.JLabel jLabel_CP;
    private javax.swing.JLabel jLabel_CPU;
    private javax.swing.JLabel jLabel_Cuadrado;
    private javax.swing.JLabel jLabel_CuadroDirec;
    private javax.swing.JLabel jLabel_DM;
    private javax.swing.JLabel jLabel_DS;
    private javax.swing.JLabel jLabel_Dato1;
    private javax.swing.JLabel jLabel_Dato2;
    private javax.swing.JLabel jLabel_Decod;
    private javax.swing.JLabel jLabel_DirM;
    private javax.swing.JLabel jLabel_DispositivosES;
    private javax.swing.JLabel jLabel_Flecha11;
    private javax.swing.JLabel jLabel_Flecha13P;
    private javax.swing.JLabel jLabel_Flecha14;
    private javax.swing.JLabel jLabel_Flecha18;
    private javax.swing.JLabel jLabel_Flecha4;
    private javax.swing.JLabel jLabel_Flecha8;
    private javax.swing.JLabel jLabel_Flecha9;
    private javax.swing.JLabel jLabel_FlechaA;
    private javax.swing.JLabel jLabel_FlechaAD;
    private javax.swing.JLabel jLabel_FlechaArri;
    private javax.swing.JLabel jLabel_GS;
    private javax.swing.JLabel jLabel_Instruccion;
    private javax.swing.JLabel jLabel_Linea1;
    private javax.swing.JLabel jLabel_Linea2;
    private javax.swing.JLabel jLabel_LineaL;
    private javax.swing.JLabel jLabel_Memoria;
    private javax.swing.JLabel jLabel_RI;
    private javax.swing.JLabel jLabel_RegistroE;
    private javax.swing.JLabel jLabel_Registros;
    private javax.swing.JLabel jLabel_RsultadoB;
    private javax.swing.JLabel jLabel_TR;
    private javax.swing.JLabel jLabel_UC;
    private javax.swing.JLabel jLabel_UnidadES;
    private javax.swing.JLabel jLabel_UnidadEje;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel_Memoria;
    private javax.swing.JPanel jPanel_Neumann;
    private javax.swing.JPanel jPanel_UnidadC;
    private javax.swing.JPanel jPanel_Unidad_Ejecucion;
    // End of variables declaration//GEN-END:variables
}
