/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Von_Neumann;

/**
 *
 * @author Langas
 */
public class Neumann_Principal extends javax.swing.JFrame {

    /**
     * Creates new form Neumann_Principal
     */
    public Neumann_Principal() {
        initComponents();
        //jLabel_Decod2.setEnabled(true);
        //jLabel_Decod2.setVisible(true);
        jLabel_Decod3.setEnabled(false);
        jLabel_Decod3.setVisible(false);
        jPanel_DDT.setEnabled(false);
        jPanel_DDT.setVisible(false);
        jPanel_RAM.setEnabled(false);
        jPanel_RAM.setVisible(false);
        jPanel_Virtual.setEnabled(false);
        jPanel_Virtual.setVisible(false);
        jLabel_CM2.setEnabled(false);
        jLabel_CM2.setVisible(false);
        jLabel_Registros2.setEnabled(false);
        jLabel_Registros2.setVisible(false);
        jPanel_Registro.setEnabled(false);
        jPanel_Registro.setVisible(false);
        jLabel_ALU2.setEnabled(false);
        jLabel_ALU2.setVisible(false);
        jPanel_ALU.setEnabled(false);
        jPanel_ALU.setVisible(false);
        jLabel_RegistroE2.setEnabled(false);
        jLabel_RegistroE2.setVisible(false);
        jPanel_RegistroE.setEnabled(false);
        jPanel_RegistroE.setVisible(false);
        jPanel_UNE.setEnabled(false);
        jPanel_UNE.setVisible(false);
        jLabel_RI2.setEnabled(false);
        jLabel_RI2.setVisible(false);
        jLabel_CP2.setEnabled(false);
        jLabel_CP2.setVisible(false);
        jLabelDecodi2.setEnabled(false);
        jLabelDecodi2.setVisible(false);
        jLabel_GS2.setEnabled(false);
        jLabel_GS2.setVisible(false);
        jLabel_Salida2.setEnabled(false);
        jLabel_Salida2.setVisible(false);
        jPanel_RegistroIR.setEnabled(false);
        jPanel_RegistroIR.setVisible(false);
        jPanel_ContadorP.setEnabled(false);
        jPanel_ContadorP.setVisible(false);
        jPanel_Decodificador.setEnabled(false);
        jPanel_Decodificador.setVisible(false);
        jPanel_GeneradorS.setEnabled(false);
        jPanel_GeneradorS.setVisible(false);
        jPanel_UnidadCo.setEnabled(false);
        jPanel_UnidadCo.setVisible(false);
        jPanel_CPU.setEnabled(false);
        jPanel_CPU.setVisible(false);
        jPanel_UnidadES.setEnabled(false);
        jPanel_UnidadES.setVisible(false);
        jPanel_UnidadES.setEnabled(false);
        jPanel_UnidadES.setVisible(false);
        jPanel_BusD.setEnabled(false);
        jPanel_BusD.setVisible(false);
        jPanel_Entrada.setEnabled(false);
        jPanel_Entrada.setVisible(false);
        jPanel_Salida.setEnabled(false);
        jPanel_Salida.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel_Neumann = new javax.swing.JPanel();
        jPanel_CPU = new javax.swing.JPanel();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jPanel_UnidadES = new javax.swing.JPanel();
        jLabel32 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jPanel_UnidadCo = new javax.swing.JPanel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jPanel_Decodificador = new javax.swing.JPanel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jPanel_ContadorP = new javax.swing.JPanel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jPanel_Salida = new javax.swing.JPanel();
        jLabel41 = new javax.swing.JLabel();
        jLabel42 = new javax.swing.JLabel();
        jPanel_RegistroIR = new javax.swing.JPanel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jPanel_GeneradorS = new javax.swing.JPanel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jPanel_UNE = new javax.swing.JPanel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jPanel_RegistroE = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jPanel_ALU = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jPanel_Entrada = new javax.swing.JPanel();
        jLabel35 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        jPanel_Registro = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jPanel_Virtual = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jPanel_BusD = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        jPanel_DDT = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jPanel_RAM = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel_Dato2 = new javax.swing.JLabel();
        jLabel_Flecha18 = new javax.swing.JLabel();
        jLabel_Flecha9 = new javax.swing.JLabel();
        jLabel_FlechaAD = new javax.swing.JLabel();
        jLabel_Flecha4 = new javax.swing.JLabel();
        jLabel_Instruccion = new javax.swing.JLabel();
        jLabel_Dato1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel_Flecha8 = new javax.swing.JLabel();
        jLabel_DirM = new javax.swing.JLabel();
        jLabel_UC = new javax.swing.JLabel();
        jLabel_Flecha14 = new javax.swing.JLabel();
        jLabel_Bus = new javax.swing.JLabel();
        jLabel_Flecha13P = new javax.swing.JLabel();
        Flecha_Grande = new javax.swing.JLabel();
        Flecha_Grande2 = new javax.swing.JLabel();
        jPanel_Memoria1 = new javax.swing.JPanel();
        jLabel_Decod2 = new javax.swing.JLabel();
        jLabel_Decod3 = new javax.swing.JLabel();
        jLabel_CuadroDirec1 = new javax.swing.JLabel();
        jLabel_CM2 = new javax.swing.JLabel();
        jLabel_Linea3 = new javax.swing.JLabel();
        jLabel_Linea4 = new javax.swing.JLabel();
        jLabel_DM1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jPanel_Unidad_Ejecucion = new javax.swing.JPanel();
        jLabel_ALU = new javax.swing.JLabel();
        jLabel_ALU2 = new javax.swing.JLabel();
        jLabel_Registros = new javax.swing.JLabel();
        jLabel_Registros2 = new javax.swing.JLabel();
        jLabel_RegistroE = new javax.swing.JLabel();
        jLabel_RegistroE2 = new javax.swing.JLabel();
        jLabel_FlechaA = new javax.swing.JLabel();
        jLabel_FlechaArri = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jPanel_UnidadC = new javax.swing.JPanel();
        jLabel_CP = new javax.swing.JLabel();
        jLabel_CP2 = new javax.swing.JLabel();
        jLabel_RI = new javax.swing.JLabel();
        jLabel_RI2 = new javax.swing.JLabel();
        jLabelDecodi = new javax.swing.JLabel();
        jLabelDecodi2 = new javax.swing.JLabel();
        jLabel_AGS = new javax.swing.JLabel();
        jLabel_AGS2 = new javax.swing.JLabel();
        jLabel_GS = new javax.swing.JLabel();
        jLabel_GS2 = new javax.swing.JLabel();
        jLabel_RsultadoB = new javax.swing.JLabel();
        jLabel_ARD = new javax.swing.JLabel();
        jLabel_Flecha11 = new javax.swing.JLabel();
        jLabel_DS = new javax.swing.JLabel();
        jLabel_TR = new javax.swing.JLabel();
        jLabel_Salida = new javax.swing.JLabel();
        jLabel_Salida2 = new javax.swing.JLabel();
        jLabel_Entrada = new javax.swing.JLabel();
        jLabel_Entrada2 = new javax.swing.JLabel();
        jPanel_ES = new javax.swing.JPanel();
        jLabel_Memoria = new javax.swing.JLabel();
        jLabel_LineaL = new javax.swing.JLabel();
        jLabel_AbajoD_UJ = new javax.swing.JLabel();
        jLabel_UnidadEje = new javax.swing.JLabel();
        jLabel_Cuadrado = new javax.swing.JLabel();
        jLabel_CPU = new javax.swing.JLabel();
        jLabel1_Flecha15 = new javax.swing.JLabel();
        jLabel_UnidadES = new javax.swing.JLabel();
        jLabel_DispositivosES = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel_Neumann.setBackground(new java.awt.Color(255, 255, 255));
        jPanel_Neumann.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel_CPU.setBackground(new java.awt.Color(0, 59, 59));
        jPanel_CPU.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 3));
        jPanel_CPU.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel_CPUMouseClicked(evt);
            }
        });
        jPanel_CPU.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel30.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/CPU2.png"))); // NOI18N
        jLabel30.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel30MouseClicked(evt);
            }
        });
        jPanel_CPU.add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 10, -1, 220));

        jLabel31.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icons8_close_window_20px_1.png"))); // NOI18N
        jLabel31.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel31.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel31MouseClicked(evt);
            }
        });
        jPanel_CPU.add(jLabel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 0, 20, 20));

        jPanel_Neumann.add(jPanel_CPU, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 520, -1, 240));

        jPanel_UnidadES.setBackground(new java.awt.Color(0, 59, 59));
        jPanel_UnidadES.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 3));
        jPanel_UnidadES.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel_UnidadESMouseClicked(evt);
            }
        });
        jPanel_UnidadES.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel32.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Unidad ES.png"))); // NOI18N
        jPanel_UnidadES.add(jLabel32, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 10, 220, 230));

        jLabel33.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icons8_close_window_20px_1.png"))); // NOI18N
        jLabel33.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel33.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel33MouseClicked(evt);
            }
        });
        jPanel_UnidadES.add(jLabel33, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 0, 20, 20));

        jPanel_Neumann.add(jPanel_UnidadES, new org.netbeans.lib.awtextra.AbsoluteConstraints(1020, 510, -1, 250));

        jPanel_UnidadCo.setBackground(new java.awt.Color(0, 59, 59));
        jPanel_UnidadCo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 3));
        jPanel_UnidadCo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel_UnidadCoMouseClicked(evt);
            }
        });
        jPanel_UnidadCo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel26.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Unidad control2.png"))); // NOI18N
        jPanel_UnidadCo.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 10, 190, 230));

        jLabel27.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icons8_close_window_20px_1.png"))); // NOI18N
        jLabel27.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel27.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel27MouseClicked(evt);
            }
        });
        jPanel_UnidadCo.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 0, 20, 20));

        jPanel_Neumann.add(jPanel_UnidadCo, new org.netbeans.lib.awtextra.AbsoluteConstraints(1020, 510, -1, 250));

        jPanel_Decodificador.setBackground(new java.awt.Color(0, 59, 59));
        jPanel_Decodificador.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 3));
        jPanel_Decodificador.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel22.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/16.png"))); // NOI18N
        jPanel_Decodificador.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 30, 160, 190));

        jLabel23.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icons8_close_window_20px_1.png"))); // NOI18N
        jLabel23.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel23.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel23MouseClicked(evt);
            }
        });
        jPanel_Decodificador.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 0, 20, 20));

        jPanel_Neumann.add(jPanel_Decodificador, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 410, -1, 240));

        jPanel_ContadorP.setBackground(new java.awt.Color(0, 59, 59));
        jPanel_ContadorP.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 3));
        jPanel_ContadorP.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel24.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/contador2.png"))); // NOI18N
        jPanel_ContadorP.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 20, 190, 200));

        jLabel25.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icons8_close_window_20px_1.png"))); // NOI18N
        jLabel25.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel25.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel25MouseClicked(evt);
            }
        });
        jPanel_ContadorP.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 0, 20, 20));

        jPanel_Neumann.add(jPanel_ContadorP, new org.netbeans.lib.awtextra.AbsoluteConstraints(990, 300, -1, 240));

        jPanel_Salida.setBackground(new java.awt.Color(0, 59, 59));
        jPanel_Salida.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 3));
        jPanel_Salida.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel41.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Dispositivos S2.png"))); // NOI18N
        jPanel_Salida.add(jLabel41, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 40, 220, 260));

        jLabel42.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icons8_close_window_20px_1.png"))); // NOI18N
        jLabel42.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel42.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel42MouseClicked(evt);
            }
        });
        jPanel_Salida.add(jLabel42, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 0, 20, 20));

        jPanel_Neumann.add(jPanel_Salida, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 140, -1, 240));

        jPanel_RegistroIR.setBackground(new java.awt.Color(0, 59, 59));
        jPanel_RegistroIR.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 3));
        jPanel_RegistroIR.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel20.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/23.png"))); // NOI18N
        jPanel_RegistroIR.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 30, 220, 170));

        jLabel21.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icons8_close_window_20px_1.png"))); // NOI18N
        jLabel21.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel21.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel21MouseClicked(evt);
            }
        });
        jPanel_RegistroIR.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 0, 20, 20));
        jPanel_RegistroIR.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, -30, -1, -1));

        jPanel_Neumann.add(jPanel_RegistroIR, new org.netbeans.lib.awtextra.AbsoluteConstraints(1010, 30, -1, 240));

        jPanel_GeneradorS.setBackground(new java.awt.Color(0, 59, 59));
        jPanel_GeneradorS.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 3));
        jPanel_GeneradorS.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel28.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/19.png"))); // NOI18N
        jLabel28.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel28MouseClicked(evt);
            }
        });
        jPanel_GeneradorS.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 10, 220, 220));

        jLabel29.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icons8_close_window_20px_1.png"))); // NOI18N
        jLabel29.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel29.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel29MouseClicked(evt);
            }
        });
        jPanel_GeneradorS.add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 0, 20, 20));

        jPanel_Neumann.add(jPanel_GeneradorS, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 510, -1, 240));

        jPanel_UNE.setBackground(new java.awt.Color(0, 51, 51));
        jPanel_UNE.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 3));
        jPanel_UNE.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/25.png"))); // NOI18N
        jPanel_UNE.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 30, 240, 190));

        jLabel19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icons8_close_window_20px_1.png"))); // NOI18N
        jLabel19.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel19.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel19MouseClicked(evt);
            }
        });
        jPanel_UNE.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 0, 20, 20));

        jPanel_Neumann.add(jPanel_UNE, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 490, -1, 240));

        jPanel_RegistroE.setBackground(new java.awt.Color(0, 59, 59));
        jPanel_RegistroE.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 3));
        jPanel_RegistroE.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Registro Estatus (Banderas) Registro de hardware que contiene información sobreel estado del procesador. Permite instrucciones parallevar la acción sobre el resultadode una instrucción anterior..png"))); // NOI18N
        jPanel_RegistroE.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 40, 220, 170));

        jLabel17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icons8_close_window_20px_1.png"))); // NOI18N
        jLabel17.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel17.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel17MouseClicked(evt);
            }
        });
        jPanel_RegistroE.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 0, 20, 20));

        jPanel_Neumann.add(jPanel_RegistroE, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 510, -1, 240));

        jPanel_ALU.setBackground(new java.awt.Color(0, 51, 51));
        jPanel_ALU.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 3));
        jPanel_ALU.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/1.png"))); // NOI18N
        jPanel_ALU.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 30, 220, 170));

        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icons8_close_window_20px_1.png"))); // NOI18N
        jLabel15.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel15.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel15MouseClicked(evt);
            }
        });
        jPanel_ALU.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 0, 20, 20));

        jPanel_Neumann.add(jPanel_ALU, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 290, -1, 240));

        jPanel_Entrada.setBackground(new java.awt.Color(0, 59, 59));
        jPanel_Entrada.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 3));
        jPanel_Entrada.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel35.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Dispositivos E2.png"))); // NOI18N
        jPanel_Entrada.add(jLabel35, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 20, 190, 200));

        jLabel36.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icons8_close_window_20px_1.png"))); // NOI18N
        jLabel36.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel36.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel36MouseClicked(evt);
            }
        });
        jPanel_Entrada.add(jLabel36, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 0, 20, 20));

        jPanel_Neumann.add(jPanel_Entrada, new org.netbeans.lib.awtextra.AbsoluteConstraints(990, 300, -1, 240));

        jPanel_Registro.setBackground(new java.awt.Color(0, 59, 59));
        jPanel_Registro.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 3));
        jPanel_Registro.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/24.png"))); // NOI18N
        jPanel_Registro.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 30, 220, 170));

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icons8_close_window_20px_1.png"))); // NOI18N
        jLabel13.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel13.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel13MouseClicked(evt);
            }
        });
        jPanel_Registro.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 0, 20, 20));

        jPanel_Neumann.add(jPanel_Registro, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 30, -1, 240));

        jPanel_Virtual.setBackground(new java.awt.Color(0, 59, 59));
        jPanel_Virtual.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 3));
        jPanel_Virtual.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Virtual.jpeg"))); // NOI18N
        jPanel_Virtual.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 0, 170, 270));

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icons8_close_window_20px_1.png"))); // NOI18N
        jLabel11.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel11.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel11MouseClicked(evt);
            }
        });
        jPanel_Virtual.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 0, 20, 20));

        jPanel_Neumann.add(jPanel_Virtual, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 470, -1, -1));

        jPanel_BusD.setBackground(new java.awt.Color(0, 59, 59));
        jPanel_BusD.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 3));
        jPanel_BusD.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Bus Datos2.png"))); // NOI18N
        jPanel_BusD.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 10, 270, 230));

        jLabel34.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icons8_close_window_20px_1.png"))); // NOI18N
        jLabel34.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel34.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel34MouseClicked(evt);
            }
        });
        jPanel_BusD.add(jLabel34, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 0, 20, 20));

        jPanel_Neumann.add(jPanel_BusD, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, -1, 250));

        jPanel_DDT.setBackground(new java.awt.Color(0, 59, 59));
        jPanel_DDT.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 3));
        jPanel_DDT.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/15.png"))); // NOI18N
        jPanel_DDT.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 320, 130));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icons8_close_window_20px_1.png"))); // NOI18N
        jLabel7.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel7MouseClicked(evt);
            }
        });
        jPanel_DDT.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 0, 20, 20));

        jPanel_Neumann.add(jPanel_DDT, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 90, 340, 240));

        jPanel_RAM.setBackground(new java.awt.Color(0, 51, 51));
        jPanel_RAM.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 3));
        jPanel_RAM.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/21.png"))); // NOI18N
        jPanel_RAM.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 30, 270, 170));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icons8_close_window_20px_1.png"))); // NOI18N
        jLabel9.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel9MouseClicked(evt);
            }
        });
        jPanel_RAM.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 0, 20, 20));

        jPanel_Neumann.add(jPanel_RAM, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 500, -1, 240));

        jLabel_Dato2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Dato.png"))); // NOI18N
        jPanel_Neumann.add(jLabel_Dato2, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 120, 50, 30));

        jLabel_Flecha18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Flecha 18_1.png"))); // NOI18N
        jPanel_Neumann.add(jLabel_Flecha18, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 130, 730, 100));

        jLabel_Flecha9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Flecha 9.png"))); // NOI18N
        jLabel_Flecha9.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel_Neumann.add(jLabel_Flecha9, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 30, 1000, 280));

        jLabel_FlechaAD.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Flecha 5.png"))); // NOI18N
        jPanel_Neumann.add(jLabel_FlechaAD, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 580, 30, 160));

        jLabel_Flecha4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Flecha 3.png"))); // NOI18N
        jPanel_Neumann.add(jLabel_Flecha4, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 130, 260, 170));

        jLabel_Instruccion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Instruccion.png"))); // NOI18N
        jPanel_Neumann.add(jLabel_Instruccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 70, -1, -1));

        jLabel_Dato1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Dato.png"))); // NOI18N
        jPanel_Neumann.add(jLabel_Dato1, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 120, 50, 30));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/CPUUnidad de Procesamiento Central.png"))); // NOI18N
        jPanel_Neumann.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 670, 270, 70));

        jLabel_Flecha8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Flecha 8.png"))); // NOI18N
        jPanel_Neumann.add(jLabel_Flecha8, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 80, 840, 230));

        jLabel_DirM.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Dirección de Memoria.png"))); // NOI18N
        jPanel_Neumann.add(jLabel_DirM, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 10, 150, 30));

        jLabel_UC.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/UNIDAD DECONTROL.png"))); // NOI18N
        jPanel_Neumann.add(jLabel_UC, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 600, 120, 40));

        jLabel_Flecha14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Flecha 14.png"))); // NOI18N
        jPanel_Neumann.add(jLabel_Flecha14, new org.netbeans.lib.awtextra.AbsoluteConstraints(980, 380, 220, 390));

        jLabel_Bus.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/BUS DE DATOS EINSTRUCCIONES.png"))); // NOI18N
        jPanel_Neumann.add(jLabel_Bus, new org.netbeans.lib.awtextra.AbsoluteConstraints(1160, 30, 130, 40));

        jLabel_Flecha13P.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Flecha 13.png"))); // NOI18N
        jPanel_Neumann.add(jLabel_Flecha13P, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 540, 50, 200));

        Flecha_Grande.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Flecha Grande.png"))); // NOI18N
        Flecha_Grande.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                Flecha_GrandeMouseMoved(evt);
            }
        });
        jPanel_Neumann.add(Flecha_Grande, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 50, 1310, -1));

        Flecha_Grande2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Flecha Grande2.png"))); // NOI18N
        Flecha_Grande2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Flecha_Grande2MouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Flecha_Grande2MouseExited(evt);
            }
        });
        jPanel_Neumann.add(Flecha_Grande2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 50, 1310, -1));

        jPanel_Memoria1.setBackground(new java.awt.Color(0, 51, 51));
        jPanel_Memoria1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel_Memoria1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel_Memoria1MouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jPanel_Memoria1MouseExited(evt);
            }
        });
        jPanel_Memoria1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel_Decod2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Decodificardor de Direcciones.png"))); // NOI18N
        jLabel_Decod2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel_Decod2.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jLabel_Decod2MouseMoved(evt);
            }
        });
        jLabel_Decod2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel_Decod2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel_Decod2MouseExited(evt);
            }
        });
        jPanel_Memoria1.add(jLabel_Decod2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 80, -1));

        jLabel_Decod3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Decodificardor de Direcciones Opacidad_1.png"))); // NOI18N
        jLabel_Decod3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel_Decod3.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jLabel_Decod3MouseDragged(evt);
            }
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jLabel_Decod3MouseMoved(evt);
            }
        });
        jLabel_Decod3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel_Decod3MouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel_Decod3MouseExited(evt);
            }
        });
        jPanel_Memoria1.add(jLabel_Decod3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 80, -1));

        jLabel_CuadroDirec1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Cuadro de Memoria.png"))); // NOI18N
        jLabel_CuadroDirec1.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jLabel_CuadroDirec1MouseMoved(evt);
            }
        });
        jLabel_CuadroDirec1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel_CuadroDirec1MouseClicked(evt);
            }
        });
        jPanel_Memoria1.add(jLabel_CuadroDirec1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 20, 139, 287));

        jLabel_CM2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Cuadro de Memoria_1.png"))); // NOI18N
        jLabel_CM2.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jLabel_CM2MouseMoved(evt);
            }
        });
        jLabel_CM2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel_CM2MouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel_CM2MouseExited(evt);
            }
        });
        jPanel_Memoria1.add(jLabel_CM2, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 20, 139, 287));

        jLabel_Linea3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Línea 4.png"))); // NOI18N
        jPanel_Memoria1.add(jLabel_Linea3, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 280, 70, 10));

        jLabel_Linea4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Línea 4.png"))); // NOI18N
        jPanel_Memoria1.add(jLabel_Linea4, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 40, 70, 10));

        jLabel_DM1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_DM1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Dirección máxima._1.png"))); // NOI18N
        jPanel_Memoria1.add(jLabel_DM1, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 280, 60, 50));

        jLabel5.setBackground(new java.awt.Color(70, 70, 70));
        jLabel5.setFont(new java.awt.Font("Open Sans", 1, 13)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(112, 112, 112));
        jLabel5.setText("0");
        jPanel_Memoria1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 10, -1, -1));

        jPanel_Neumann.add(jPanel_Memoria1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 280, 370, 320));

        jPanel_Unidad_Ejecucion.setBackground(new java.awt.Color(0, 51, 51));
        jPanel_Unidad_Ejecucion.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel_Unidad_Ejecucion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel_Unidad_EjecucionMouseClicked(evt);
            }
        });
        jPanel_Unidad_Ejecucion.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel_ALU.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/ALU.png"))); // NOI18N
        jLabel_ALU.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jLabel_ALUMouseMoved(evt);
            }
        });
        jPanel_Unidad_Ejecucion.add(jLabel_ALU, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 160, 210, 80));

        jLabel_ALU2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/ALU2.png"))); // NOI18N
        jLabel_ALU2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel_ALU2MouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel_ALU2MouseExited(evt);
            }
        });
        jPanel_Unidad_Ejecucion.add(jLabel_ALU2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 160, 210, 80));

        jLabel_Registros.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Registros.png"))); // NOI18N
        jLabel_Registros.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jLabel_RegistrosMouseMoved(evt);
            }
        });
        jPanel_Unidad_Ejecucion.add(jLabel_Registros, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 40, 290, 70));

        jLabel_Registros2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Registros_1.png"))); // NOI18N
        jLabel_Registros2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel_Registros2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel_Registros2MouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel_Registros2MouseExited(evt);
            }
        });
        jPanel_Unidad_Ejecucion.add(jLabel_Registros2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 40, 290, 70));

        jLabel_RegistroE.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Registro de Estatus.png"))); // NOI18N
        jLabel_RegistroE.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jLabel_RegistroEMouseMoved(evt);
            }
        });
        jPanel_Unidad_Ejecucion.add(jLabel_RegistroE, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 290, 210, 90));

        jLabel_RegistroE2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Registro de Estatus2.png"))); // NOI18N
        jLabel_RegistroE2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel_RegistroE2MouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel_RegistroE2MouseExited(evt);
            }
        });
        jPanel_Unidad_Ejecucion.add(jLabel_RegistroE2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 290, 210, 90));

        jLabel_FlechaA.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Fecha.png"))); // NOI18N
        jPanel_Unidad_Ejecucion.add(jLabel_FlechaA, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 100, 20, 70));

        jLabel_FlechaArri.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Fecha 2.png"))); // NOI18N
        jPanel_Unidad_Ejecucion.add(jLabel_FlechaArri, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 110, 20, 60));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Fecha.png"))); // NOI18N
        jPanel_Unidad_Ejecucion.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 230, 20, 60));

        jPanel_Neumann.add(jPanel_Unidad_Ejecucion, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 190, 350, 410));

        jPanel_UnidadC.setBackground(new java.awt.Color(0, 51, 51));
        jPanel_UnidadC.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel_UnidadC.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel_UnidadCMouseClicked(evt);
            }
        });
        jPanel_UnidadC.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel_CP.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Contador de Programa.png"))); // NOI18N
        jLabel_CP.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel_CP.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jLabel_CPMouseMoved(evt);
            }
        });
        jPanel_UnidadC.add(jLabel_CP, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 40, 150, 90));

        jLabel_CP2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Contador de Programa_1.png"))); // NOI18N
        jLabel_CP2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel_CP2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel_CP2MouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel_CP2MouseExited(evt);
            }
        });
        jPanel_UnidadC.add(jLabel_CP2, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 40, 150, 90));

        jLabel_RI.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Registro de Instrucciones.png"))); // NOI18N
        jLabel_RI.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel_RI.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jLabel_RIMouseMoved(evt);
            }
        });
        jPanel_UnidadC.add(jLabel_RI, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, 150, 90));

        jLabel_RI2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Registro de Instrucciones_1.png"))); // NOI18N
        jLabel_RI2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel_RI2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel_RI2MouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel_RI2MouseExited(evt);
            }
        });
        jPanel_UnidadC.add(jLabel_RI2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, 150, 90));

        jLabelDecodi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Decodificador.png"))); // NOI18N
        jLabelDecodi.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabelDecodi.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jLabelDecodiMouseMoved(evt);
            }
        });
        jPanel_UnidadC.add(jLabelDecodi, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, 150, 40));

        jLabelDecodi2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Decodificador_1.png"))); // NOI18N
        jLabelDecodi2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabelDecodi2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelDecodi2MouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabelDecodi2MouseExited(evt);
            }
        });
        jPanel_UnidadC.add(jLabelDecodi2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, 150, 40));

        jLabel_AGS.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Fecha 12.png"))); // NOI18N
        jPanel_UnidadC.add(jLabel_AGS, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 190, 30, 40));

        jLabel_AGS2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Fecha 12.png"))); // NOI18N
        jPanel_UnidadC.add(jLabel_AGS2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 190, 30, 40));

        jLabel_GS.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Generador de Señales.png"))); // NOI18N
        jLabel_GS.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel_GS.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jLabel_GSMouseMoved(evt);
            }
        });
        jLabel_GS.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel_GSMouseClicked(evt);
            }
        });
        jPanel_UnidadC.add(jLabel_GS, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 210, 150, 100));

        jLabel_GS2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Generador de Señales_1.png"))); // NOI18N
        jLabel_GS2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel_GS2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel_GS2MouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel_GS2MouseExited(evt);
            }
        });
        jPanel_UnidadC.add(jLabel_GS2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 210, 150, 100));

        jLabel_RsultadoB.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Resultado y banderas delRegistro deEstatus.png"))); // NOI18N
        jPanel_UnidadC.add(jLabel_RsultadoB, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 200, 110, 90));

        jLabel_ARD.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Fecha 10.png"))); // NOI18N
        jPanel_UnidadC.add(jLabel_ARD, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 120, 20, 50));

        jLabel_Flecha11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Flecha 11.png"))); // NOI18N
        jPanel_UnidadC.add(jLabel_Flecha11, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 120, 180, 40));

        jLabel_DS.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Dirección (Salto).png"))); // NOI18N
        jPanel_UnidadC.add(jLabel_DS, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 160, 110, 20));

        jLabel_TR.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Trabajo a realizar.png"))); // NOI18N
        jPanel_UnidadC.add(jLabel_TR, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 320, 120, 30));

        jPanel_Neumann.add(jPanel_UnidadC, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 240, 360, 360));

        jLabel_Salida.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Flecha 16.png"))); // NOI18N
        jLabel_Salida.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel_Salida.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jLabel_SalidaMouseMoved(evt);
            }
        });
        jPanel_Neumann.add(jLabel_Salida, new org.netbeans.lib.awtextra.AbsoluteConstraints(1260, 320, 60, 40));

        jLabel_Salida2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Flecha 16_1.png"))); // NOI18N
        jLabel_Salida2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel_Salida2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel_Salida2MouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel_Salida2MouseExited(evt);
            }
        });
        jPanel_Neumann.add(jLabel_Salida2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1260, 320, 60, 40));

        jLabel_Entrada.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Flecha 17.png"))); // NOI18N
        jLabel_Entrada.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel_Entrada.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jLabel_EntradaMouseMoved(evt);
            }
        });
        jPanel_Neumann.add(jLabel_Entrada, new org.netbeans.lib.awtextra.AbsoluteConstraints(1260, 380, 60, 40));

        jLabel_Entrada2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Flecha 17_1.png"))); // NOI18N
        jLabel_Entrada2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel_Entrada2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel_Entrada2MouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel_Entrada2MouseExited(evt);
            }
        });
        jPanel_Neumann.add(jLabel_Entrada2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1260, 380, 60, 40));

        jPanel_ES.setBackground(new java.awt.Color(0, 51, 51));
        jPanel_ES.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel_ES.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel_ESMouseClicked(evt);
            }
        });
        jPanel_ES.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel_Neumann.add(jPanel_ES, new org.netbeans.lib.awtextra.AbsoluteConstraints(1210, 200, 60, 400));

        jLabel_Memoria.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/MEMORIA.png"))); // NOI18N
        jPanel_Neumann.add(jLabel_Memoria, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 600, 90, 30));

        jLabel_LineaL.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Flecha 6.png"))); // NOI18N
        jPanel_Neumann.add(jLabel_LineaL, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 730, 1030, 10));

        jLabel_AbajoD_UJ.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Flecha 7.png"))); // NOI18N
        jPanel_Neumann.add(jLabel_AbajoD_UJ, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 590, 20, 150));

        jLabel_UnidadEje.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/UNIDAD DEEJECUCION.png"))); // NOI18N
        jPanel_Neumann.add(jLabel_UnidadEje, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 600, 100, 40));

        jLabel_Cuadrado.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Cuadro.png"))); // NOI18N
        jPanel_Neumann.add(jLabel_Cuadrado, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 160, 810, 520));

        jLabel_CPU.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel_CPU.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel_CPUMouseClicked(evt);
            }
        });
        jPanel_Neumann.add(jLabel_CPU, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 680, 260, 50));

        jLabel1_Flecha15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Flecha 15.png"))); // NOI18N
        jPanel_Neumann.add(jLabel1_Flecha15, new org.netbeans.lib.awtextra.AbsoluteConstraints(1230, 600, 20, 130));

        jLabel_UnidadES.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/UNIDADE-S (I-O).png"))); // NOI18N
        jPanel_Neumann.add(jLabel_UnidadES, new org.netbeans.lib.awtextra.AbsoluteConstraints(1250, 600, 70, 60));

        jLabel_DispositivosES.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/DispositivosE-S.png"))); // NOI18N
        jLabel_DispositivosES.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel_Neumann.add(jLabel_DispositivosES, new org.netbeans.lib.awtextra.AbsoluteConstraints(1270, 350, 80, 50));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icons8_close_window_20px_2.png"))); // NOI18N
        jLabel1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });
        jPanel_Neumann.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1350, 0, 20, 20));

        getContentPane().add(jPanel_Neumann, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1366, 868));

        setSize(new java.awt.Dimension(1366, 832));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jPanel_Memoria1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel_Memoria1MouseClicked
        // TODO add your handling code here:
        jPanel_RAM.setEnabled(true);
        jPanel_RAM.setVisible(true);
    }//GEN-LAST:event_jPanel_Memoria1MouseClicked

    private void jPanel_Memoria1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel_Memoria1MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_jPanel_Memoria1MouseExited

    private void jLabel_Decod2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_Decod2MouseExited
        // TODO add your handling code here:
       

    }//GEN-LAST:event_jLabel_Decod2MouseExited

    private void jLabel_Decod2MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_Decod2MouseMoved
        // TODO add your handling code here:
        //jLabel_Decod2.setEnabled(false);
        jLabel_Decod2.setVisible(false);
       // jLabel_Decod3.setEnabled(true);
        jLabel_Decod3.setVisible(true);
        jLabel_Flecha9.setVisible(false);
        jLabel_Flecha9.setVisible(true);

    }//GEN-LAST:event_jLabel_Decod2MouseMoved

    private void jLabel_Decod3MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_Decod3MouseExited
        // TODO add your handling code here:
       // jLabel_Decod3.setEnabled(false);
        jLabel_Decod3.setVisible(false);
        //jLabel_Decod2.setEnabled(true);
        jLabel_Decod2.setVisible(true);
        jLabel_Flecha9.setVisible(false);
        jLabel_Flecha9.setVisible(true);

    }//GEN-LAST:event_jLabel_Decod3MouseExited

    private void jLabel_Decod3MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_Decod3MouseMoved
        // TODO add your handling code here:

    }//GEN-LAST:event_jLabel_Decod3MouseMoved

    private void jLabel7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel7MouseClicked
        // TODO add your handling code here:
        jPanel_DDT.setEnabled(false);
        jPanel_DDT.setVisible(false);
    }//GEN-LAST:event_jLabel7MouseClicked

    private void jLabel_Decod3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_Decod3MouseClicked
        // TODO add your handling code here:
        jPanel_DDT.setEnabled(true);
        jPanel_DDT.setVisible(true);
    }//GEN-LAST:event_jLabel_Decod3MouseClicked

    private void jLabel9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel9MouseClicked
        // TODO add your handling code here:
        jPanel_RAM.setEnabled(false);
        jPanel_RAM.setVisible(false);
    }//GEN-LAST:event_jLabel9MouseClicked

    private void jLabel11MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel11MouseClicked
        // TODO add your handling code here:
        jPanel_Virtual.setEnabled(false);
        jPanel_Virtual.setVisible(false);
    }//GEN-LAST:event_jLabel11MouseClicked

    private void jLabel_CuadroDirec1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_CuadroDirec1MouseClicked
        // TODO add your handling code here:

    }//GEN-LAST:event_jLabel_CuadroDirec1MouseClicked

    private void jLabel_Decod2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_Decod2MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel_Decod2MouseEntered

    private void jLabel_Decod3MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_Decod3MouseDragged
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel_Decod3MouseDragged

    private void jLabel_CuadroDirec1MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_CuadroDirec1MouseMoved
        // TODO add your handling code here:
        //jLabel_Decod2.setEnabled(false);
        jLabel_CuadroDirec1.setVisible(false);
       // jLabel_Decod3.setEnabled(true);
        jLabel_CM2.setVisible(true);
        jLabel_Flecha4.setVisible(false);
        jLabel_Flecha4.setVisible(true);
    }//GEN-LAST:event_jLabel_CuadroDirec1MouseMoved

    private void jLabel_CM2MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_CM2MouseMoved
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jLabel_CM2MouseMoved

    private void jLabel_CM2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_CM2MouseExited
        // TODO add your handling code here:
        // jLabel_Decod3.setEnabled(false);
        jLabel_CM2.setVisible(false);
        //jLabel_Decod2.setEnabled(true);
        jLabel_CuadroDirec1.setVisible(true);
        jLabel_Flecha4.setVisible(false);
        jLabel_Flecha4.setVisible(true);
    }//GEN-LAST:event_jLabel_CM2MouseExited

    private void jLabel_CM2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_CM2MouseClicked
        // TODO add your handling code here:
        jPanel_Virtual.setEnabled(true);
        jPanel_Virtual.setVisible(true);
    }//GEN-LAST:event_jLabel_CM2MouseClicked

    private void jLabel13MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel13MouseClicked
        // TODO add your handling code here:
        jPanel_Registro.setEnabled(false);
        jPanel_Registro.setVisible(false);
    }//GEN-LAST:event_jLabel13MouseClicked

    private void jLabel_RegistrosMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_RegistrosMouseMoved
        // TODO add your handling code here:
        //jLabel_Decod2.setEnabled(false);
        jLabel_Registros.setVisible(false);
       // jLabel_Decod3.setEnabled(true);
        jLabel_Registros2.setVisible(true);
        jLabel_Flecha18.setVisible(false);
        jLabel_Flecha18.setVisible(true);
    }//GEN-LAST:event_jLabel_RegistrosMouseMoved

    private void jLabel_Registros2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_Registros2MouseExited
        // TODO add your handling code here:
        // jLabel_Decod3.setEnabled(false);
        jLabel_Registros2.setVisible(false);
        //jLabel_Decod2.setEnabled(true);
        jLabel_Registros.setVisible(true);
        jLabel_Flecha18.setVisible(false);
        jLabel_Flecha18.setVisible(true);
    }//GEN-LAST:event_jLabel_Registros2MouseExited

    private void jLabel_Registros2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_Registros2MouseClicked
        // TODO add your handling code here:
        jPanel_Registro.setEnabled(true);
        jPanel_Registro.setVisible(true);
    }//GEN-LAST:event_jLabel_Registros2MouseClicked

    private void jLabel_ALUMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_ALUMouseMoved
        // TODO add your handling code here:
                //jLabel_Decod2.setEnabled(false);
        jLabel_ALU.setVisible(false);
       // jLabel_Decod3.setEnabled(true);
        jLabel_ALU2.setVisible(true);
    }//GEN-LAST:event_jLabel_ALUMouseMoved

    private void jLabel_ALU2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_ALU2MouseExited
        // TODO add your handling code here:
        
        // jLabel_Decod3.setEnabled(false);
        jLabel_ALU2.setVisible(false);
        //jLabel_Decod2.setEnabled(true);
        jLabel_ALU.setVisible(true);
    }//GEN-LAST:event_jLabel_ALU2MouseExited

    private void jLabel15MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel15MouseClicked
        // TODO add your handling code here:
        jPanel_ALU.setEnabled(false);
        jPanel_ALU.setVisible(false);
    }//GEN-LAST:event_jLabel15MouseClicked

    private void jLabel_ALU2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_ALU2MouseClicked
        // TODO add your handling code here:
        jPanel_ALU.setEnabled(true);
        jPanel_ALU.setVisible(true);
    }//GEN-LAST:event_jLabel_ALU2MouseClicked

    private void jLabel_RegistroEMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_RegistroEMouseMoved
        // TODO add your handling code here:
                //jLabel_Decod2.setEnabled(false);
        jLabel_RegistroE.setVisible(false);
       // jLabel_Decod3.setEnabled(true);
        jLabel_RegistroE2.setVisible(true);
        jLabel_Flecha4.setVisible(false);
        jLabel_Flecha4.setVisible(true);
    }//GEN-LAST:event_jLabel_RegistroEMouseMoved

    private void jLabel_RegistroE2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_RegistroE2MouseExited
        // TODO add your handling code here:
        
        // jLabel_Decod3.setEnabled(false);
        jLabel_RegistroE2.setVisible(false);
        //jLabel_Decod2.setEnabled(true);
        jLabel_RegistroE.setVisible(true);
        jLabel_Flecha4.setVisible(false);
        jLabel_Flecha4.setVisible(true);
    }//GEN-LAST:event_jLabel_RegistroE2MouseExited

    private void jLabel17MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel17MouseClicked
        // TODO add your handling code here:
        jPanel_RegistroE.setEnabled(false);
        jPanel_RegistroE.setVisible(false);
    }//GEN-LAST:event_jLabel17MouseClicked

    private void jLabel_RegistroE2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_RegistroE2MouseClicked
        // TODO add your handling code here:
        jPanel_RegistroE.setEnabled(true);
        jPanel_RegistroE.setVisible(true);
    }//GEN-LAST:event_jLabel_RegistroE2MouseClicked

    private void jLabel19MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel19MouseClicked
        // TODO add your handling code here:
        jPanel_UNE.setEnabled(false);
        jPanel_UNE.setVisible(false);
    }//GEN-LAST:event_jLabel19MouseClicked

    private void jPanel_Unidad_EjecucionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel_Unidad_EjecucionMouseClicked
        // TODO add your handling code here:
        jPanel_UNE.setEnabled(true);
        jPanel_UNE.setVisible(true);
    }//GEN-LAST:event_jPanel_Unidad_EjecucionMouseClicked

    private void jLabel_RIMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_RIMouseMoved
        // TODO add your handling code here:
        jLabel_RI.setVisible(false);
        // jLabel_Decod3.setEnabled(true);
        jLabel_RI2.setVisible(true);
        jLabel_Flecha4.setVisible(false);
        jLabel_Flecha4.setVisible(true);
    }//GEN-LAST:event_jLabel_RIMouseMoved

    private void jLabel_RI2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_RI2MouseExited
        // TODO add your handling code here:
        jLabel_RI2.setVisible(false);
        // jLabel_Decod3.setEnabled(true);
        jLabel_RI.setVisible(true);
        jLabel_Flecha4.setVisible(false);
        jLabel_Flecha4.setVisible(true);
    }//GEN-LAST:event_jLabel_RI2MouseExited

    private void jLabel_CPMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_CPMouseMoved
        // TODO add your handling code here:}
        jLabel_CP.setVisible(false);
        // jLabel_Decod3.setEnabled(true);
        jLabel_CP2.setVisible(true);
        jLabel_Flecha4.setVisible(false);
        jLabel_Flecha4.setVisible(true);
    }//GEN-LAST:event_jLabel_CPMouseMoved

    private void jLabel_CP2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_CP2MouseExited
        // TODO add your handling code here:
        jLabel_CP2.setVisible(false);
        // jLabel_Decod3.setEnabled(true);
        jLabel_CP.setVisible(true);
        jLabel_Flecha4.setVisible(false);
        jLabel_Flecha4.setVisible(true);
    }//GEN-LAST:event_jLabel_CP2MouseExited

    private void jLabelDecodiMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelDecodiMouseMoved
        // TODO add your handling code here:
        jLabelDecodi.setVisible(false);
        // jLabel_Decod3.setEnabled(true);
        jLabelDecodi2.setVisible(true);
        jLabel_Flecha4.setVisible(false);
        jLabel_Flecha4.setVisible(true);
    }//GEN-LAST:event_jLabelDecodiMouseMoved

    private void jLabelDecodi2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelDecodi2MouseExited
        // TODO add your handling code here:
        jLabelDecodi2.setVisible(false);
        // jLabel_Decod3.setEnabled(true);
        jLabelDecodi.setVisible(true);
        jLabel_Flecha4.setVisible(false);
        jLabel_Flecha4.setVisible(true);
    }//GEN-LAST:event_jLabelDecodi2MouseExited

    private void jLabel_GSMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_GSMouseMoved
        // TODO add your handling code here:
        
        jLabel_GS.setVisible(false);
        // jLabel_Decod3.setEnabled(true);
        jLabel_GS2.setVisible(true);
        jLabel_Flecha4.setVisible(false);
        jLabel_Flecha4.setVisible(true);
    }//GEN-LAST:event_jLabel_GSMouseMoved

    private void jLabel_GS2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_GS2MouseExited
        // TODO add your handling code here:
        jLabel_GS2.setVisible(false);
        // jLabel_Decod3.setEnabled(true);
        jLabel_GS.setVisible(true);
        jLabel_Flecha4.setVisible(false);
        jLabel_Flecha4.setVisible(true);
    }//GEN-LAST:event_jLabel_GS2MouseExited

    private void jLabel_SalidaMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_SalidaMouseMoved
        // TODO add your handling code here:
        jLabel_Salida.setVisible(false);
        // jLabel_Decod3.setEnabled(true);
        jLabel_Salida2.setVisible(true);
        jLabel_Flecha4.setVisible(false);
        jLabel_Flecha4.setVisible(true);
    }//GEN-LAST:event_jLabel_SalidaMouseMoved

    private void jLabel_Salida2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_Salida2MouseExited
        // TODO add your handling code here:
        jLabel_Salida2.setVisible(false);
        // jLabel_Decod3.setEnabled(true);
        jLabel_Salida.setVisible(true);
        jLabel_Flecha4.setVisible(false);
        jLabel_Flecha4.setVisible(true);
    }//GEN-LAST:event_jLabel_Salida2MouseExited

    private void jLabel_EntradaMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_EntradaMouseMoved
        // TODO add your handling code here:
        jLabel_Entrada.setVisible(false);
        // jLabel_Decod3.setEnabled(true);
        jLabel_Entrada2.setVisible(true);
        jLabel_Flecha4.setVisible(false);
        jLabel_Flecha4.setVisible(true);
    }//GEN-LAST:event_jLabel_EntradaMouseMoved

    private void jLabel_Entrada2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_Entrada2MouseExited
        // TODO add your handling code here:
        jLabel_Entrada2.setVisible(false);
        // jLabel_Decod3.setEnabled(true);
        jLabel_Entrada.setVisible(true);
        jLabel_Flecha4.setVisible(false);
        jLabel_Flecha4.setVisible(true);
    }//GEN-LAST:event_jLabel_Entrada2MouseExited

    private void jLabel21MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel21MouseClicked
        // TODO add your handling code here:
        jPanel_RegistroIR.setEnabled(false);
        jPanel_RegistroIR.setVisible(false);
    }//GEN-LAST:event_jLabel21MouseClicked

    private void jLabel_RI2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_RI2MouseClicked
        // TODO add your handling code here:
        jPanel_RegistroIR.setEnabled(true);
        jPanel_RegistroIR.setVisible(true);
    }//GEN-LAST:event_jLabel_RI2MouseClicked

    private void jLabel25MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel25MouseClicked
        // TODO add your handling code here:
        jPanel_ContadorP.setEnabled(false);
        jPanel_ContadorP.setVisible(false);
    }//GEN-LAST:event_jLabel25MouseClicked

    private void jLabel_CP2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_CP2MouseClicked
        // TODO add your handling code here:
        jPanel_ContadorP.setEnabled(true);
        jPanel_ContadorP.setVisible(true);
    }//GEN-LAST:event_jLabel_CP2MouseClicked

    private void jLabel23MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel23MouseClicked
        // TODO add your handling code here:
        jPanel_Decodificador.setEnabled(false);
        jPanel_Decodificador.setVisible(false);
    }//GEN-LAST:event_jLabel23MouseClicked

    private void jLabelDecodi2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelDecodi2MouseClicked
        // TODO add your handling code here:
        jPanel_Decodificador.setEnabled(true);
        jPanel_Decodificador.setVisible(true);
    }//GEN-LAST:event_jLabelDecodi2MouseClicked

    private void jLabel29MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel29MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel29MouseClicked

    private void jLabel_GSMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_GSMouseClicked
        // TODO add your handling code here:

    }//GEN-LAST:event_jLabel_GSMouseClicked

    private void jLabel28MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel28MouseClicked
        // TODO add your handling code here:
        jPanel_Decodificador.setEnabled(false);
        jPanel_Decodificador.setVisible(false);
    }//GEN-LAST:event_jLabel28MouseClicked

    private void jLabel_GS2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_GS2MouseClicked
        // TODO add your handling code here:
        jPanel_Decodificador.setEnabled(true);
        jPanel_Decodificador.setVisible(true);
    }//GEN-LAST:event_jLabel_GS2MouseClicked

    private void jLabel27MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel27MouseClicked
        // TODO add your handling code here:
        jPanel_UnidadCo.setEnabled(false);
        jPanel_UnidadCo.setVisible(false);
    }//GEN-LAST:event_jLabel27MouseClicked

    private void jPanel_UnidadCoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel_UnidadCoMouseClicked
        // TODO add your handling code here:
        jPanel_GeneradorS.setEnabled(true);
        jPanel_GeneradorS.setVisible(true);
    }//GEN-LAST:event_jPanel_UnidadCoMouseClicked

    private void jPanel_UnidadCMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel_UnidadCMouseClicked
        // TODO add your handling code here:
        jPanel_UnidadCo.setEnabled(true);
        jPanel_UnidadCo.setVisible(true);
    }//GEN-LAST:event_jPanel_UnidadCMouseClicked

    private void jLabel30MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel30MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel30MouseClicked

    private void jLabel31MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel31MouseClicked
        // TODO add your handling code here:
        
        jPanel_CPU.setEnabled(false);
        jPanel_CPU.setVisible(false);
    }//GEN-LAST:event_jLabel31MouseClicked

    private void jLabel_CPUMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_CPUMouseClicked
        // TODO add your handling code here:
        jPanel_CPU.setEnabled(true);
        jPanel_CPU.setVisible(true);
    }//GEN-LAST:event_jLabel_CPUMouseClicked

    private void jPanel_CPUMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel_CPUMouseClicked
        // TODO add your handling code here:
        

    }//GEN-LAST:event_jPanel_CPUMouseClicked

    private void jLabel33MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel33MouseClicked
        // TODO add your handling code here:
        jPanel_UnidadES.setEnabled(false);
        jPanel_UnidadES.setVisible(false);
    }//GEN-LAST:event_jLabel33MouseClicked

    private void jPanel_UnidadESMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel_UnidadESMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jPanel_UnidadESMouseClicked

    private void jPanel_ESMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel_ESMouseClicked
        // TODO add your handling code here:
        jPanel_UnidadES.setEnabled(true);
        jPanel_UnidadES.setVisible(true);
    }//GEN-LAST:event_jPanel_ESMouseClicked

    private void Flecha_GrandeMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Flecha_GrandeMouseMoved
        // TODO add your handling code here:
        //jLabel_Decod2.setEnabled(false);
        Flecha_Grande.setVisible(false);
       // jLabel_Decod3.setEnabled(true);
        Flecha_Grande2.setVisible(true);
    }//GEN-LAST:event_Flecha_GrandeMouseMoved

    private void Flecha_Grande2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Flecha_Grande2MouseExited
        // TODO add your handling code here:
        // jLabel_Decod3.setEnabled(false);
        Flecha_Grande2.setVisible(false);
        //jLabel_Decod2.setEnabled(true);
        Flecha_Grande.setVisible(true);
    }//GEN-LAST:event_Flecha_Grande2MouseExited

    private void jLabel34MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel34MouseClicked
        // TODO add your handling code here:
        jPanel_BusD.setEnabled(false);
        jPanel_BusD.setVisible(false);
    }//GEN-LAST:event_jLabel34MouseClicked

    private void Flecha_Grande2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Flecha_Grande2MouseClicked
        // TODO add your handling code here:
        jPanel_BusD.setEnabled(true);
        jPanel_BusD.setVisible(true);
    }//GEN-LAST:event_Flecha_Grande2MouseClicked

    private void jLabel36MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel36MouseClicked
        // TODO add your handling code here:
        jPanel_Entrada.setEnabled(false);
        jPanel_Entrada.setVisible(false);
    }//GEN-LAST:event_jLabel36MouseClicked

    private void jLabel_Entrada2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_Entrada2MouseClicked
        // TODO add your handling code here:
        jPanel_Entrada.setEnabled(true);
        jPanel_Entrada.setVisible(true);
    }//GEN-LAST:event_jLabel_Entrada2MouseClicked

    private void jLabel42MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel42MouseClicked
        // TODO add your handling code here:
        jPanel_Salida.setEnabled(false);
        jPanel_Salida.setVisible(false);
    }//GEN-LAST:event_jLabel42MouseClicked

    private void jLabel_Salida2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_Salida2MouseClicked
        // TODO add your handling code here:
        jPanel_Salida.setEnabled(true);
        jPanel_Salida.setVisible(true);
    }//GEN-LAST:event_jLabel_Salida2MouseClicked

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jLabel1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Neumann_Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Neumann_Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Neumann_Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Neumann_Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Neumann_Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Flecha_Grande;
    private javax.swing.JLabel Flecha_Grande2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel1_Flecha15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelDecodi;
    private javax.swing.JLabel jLabelDecodi2;
    private javax.swing.JLabel jLabel_AGS;
    private javax.swing.JLabel jLabel_AGS2;
    private javax.swing.JLabel jLabel_ALU;
    private javax.swing.JLabel jLabel_ALU2;
    private javax.swing.JLabel jLabel_ARD;
    private javax.swing.JLabel jLabel_AbajoD_UJ;
    private javax.swing.JLabel jLabel_Bus;
    private javax.swing.JLabel jLabel_CM2;
    private javax.swing.JLabel jLabel_CP;
    private javax.swing.JLabel jLabel_CP2;
    private javax.swing.JLabel jLabel_CPU;
    private javax.swing.JLabel jLabel_Cuadrado;
    private javax.swing.JLabel jLabel_CuadroDirec1;
    private javax.swing.JLabel jLabel_DM1;
    private javax.swing.JLabel jLabel_DS;
    private javax.swing.JLabel jLabel_Dato1;
    private javax.swing.JLabel jLabel_Dato2;
    private javax.swing.JLabel jLabel_Decod2;
    private javax.swing.JLabel jLabel_Decod3;
    private javax.swing.JLabel jLabel_DirM;
    private javax.swing.JLabel jLabel_DispositivosES;
    private javax.swing.JLabel jLabel_Entrada;
    private javax.swing.JLabel jLabel_Entrada2;
    private javax.swing.JLabel jLabel_Flecha11;
    private javax.swing.JLabel jLabel_Flecha13P;
    private javax.swing.JLabel jLabel_Flecha14;
    private javax.swing.JLabel jLabel_Flecha18;
    private javax.swing.JLabel jLabel_Flecha4;
    private javax.swing.JLabel jLabel_Flecha8;
    private javax.swing.JLabel jLabel_Flecha9;
    private javax.swing.JLabel jLabel_FlechaA;
    private javax.swing.JLabel jLabel_FlechaAD;
    private javax.swing.JLabel jLabel_FlechaArri;
    private javax.swing.JLabel jLabel_GS;
    private javax.swing.JLabel jLabel_GS2;
    private javax.swing.JLabel jLabel_Instruccion;
    private javax.swing.JLabel jLabel_Linea3;
    private javax.swing.JLabel jLabel_Linea4;
    private javax.swing.JLabel jLabel_LineaL;
    private javax.swing.JLabel jLabel_Memoria;
    private javax.swing.JLabel jLabel_RI;
    private javax.swing.JLabel jLabel_RI2;
    private javax.swing.JLabel jLabel_RegistroE;
    private javax.swing.JLabel jLabel_RegistroE2;
    private javax.swing.JLabel jLabel_Registros;
    private javax.swing.JLabel jLabel_Registros2;
    private javax.swing.JLabel jLabel_RsultadoB;
    private javax.swing.JLabel jLabel_Salida;
    private javax.swing.JLabel jLabel_Salida2;
    private javax.swing.JLabel jLabel_TR;
    private javax.swing.JLabel jLabel_UC;
    private javax.swing.JLabel jLabel_UnidadES;
    private javax.swing.JLabel jLabel_UnidadEje;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel_ALU;
    private javax.swing.JPanel jPanel_BusD;
    private javax.swing.JPanel jPanel_CPU;
    private javax.swing.JPanel jPanel_ContadorP;
    private javax.swing.JPanel jPanel_DDT;
    private javax.swing.JPanel jPanel_Decodificador;
    private javax.swing.JPanel jPanel_ES;
    private javax.swing.JPanel jPanel_Entrada;
    private javax.swing.JPanel jPanel_GeneradorS;
    private javax.swing.JPanel jPanel_Memoria1;
    private javax.swing.JPanel jPanel_Neumann;
    private javax.swing.JPanel jPanel_RAM;
    private javax.swing.JPanel jPanel_Registro;
    private javax.swing.JPanel jPanel_RegistroE;
    private javax.swing.JPanel jPanel_RegistroIR;
    private javax.swing.JPanel jPanel_Salida;
    private javax.swing.JPanel jPanel_UNE;
    private javax.swing.JPanel jPanel_UnidadC;
    private javax.swing.JPanel jPanel_UnidadCo;
    private javax.swing.JPanel jPanel_UnidadES;
    private javax.swing.JPanel jPanel_Unidad_Ejecucion;
    private javax.swing.JPanel jPanel_Virtual;
    // End of variables declaration//GEN-END:variables
}
