/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Von_Neumann;

/**
 *
 * @author Langas
 */
public class Neumann_Principal extends javax.swing.JFrame {

    /**
     * Creates new form Neumann_Principal
     */
    public Neumann_Principal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel_Neumann = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel_FlechaAD = new javax.swing.JLabel();
        jLabel_Flecha4 = new javax.swing.JLabel();
        Flecha_Grande = new javax.swing.JLabel();
        jPanel_Memoria = new javax.swing.JPanel();
        jLabel_Decod = new javax.swing.JLabel();
        jLabel_CuadroDirec = new javax.swing.JLabel();
        jLabel_Linea1 = new javax.swing.JLabel();
        jLabel_Linea2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel_Unidad_Ejecucion = new javax.swing.JPanel();
        jLabel_ALU = new javax.swing.JLabel();
        jLabel_Registros = new javax.swing.JLabel();
        jLabel_RegistroE = new javax.swing.JLabel();
        jLabel_FlechaA = new javax.swing.JLabel();
        jLabel_FlechaArri = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jPanel_UnidadC = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel_Memoria = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel_UnidadEje = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel_Neumann.setBackground(new java.awt.Color(255, 255, 255));
        jPanel_Neumann.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Cuadro.png"))); // NOI18N
        jPanel_Neumann.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 160, 810, 520));

        jLabel_FlechaAD.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Flecha 5.png"))); // NOI18N
        jPanel_Neumann.add(jLabel_FlechaAD, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 580, 30, 160));

        jLabel_Flecha4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Flecha 3.png"))); // NOI18N
        jPanel_Neumann.add(jLabel_Flecha4, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 130, 260, 170));

        Flecha_Grande.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Flecha Grande.png"))); // NOI18N
        jPanel_Neumann.add(Flecha_Grande, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 50, 1310, -1));

        jPanel_Memoria.setBackground(new java.awt.Color(0, 51, 51));
        jPanel_Memoria.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel_Decod.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Decodificardor de Direcciones.png"))); // NOI18N
        jPanel_Memoria.add(jLabel_Decod, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 80, 300));

        jLabel_CuadroDirec.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Cuadro de Memoria.png"))); // NOI18N
        jPanel_Memoria.add(jLabel_CuadroDirec, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 20, 139, 287));

        jLabel_Linea1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Línea 4.png"))); // NOI18N
        jPanel_Memoria.add(jLabel_Linea1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 280, 70, 10));

        jLabel_Linea2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Línea 4.png"))); // NOI18N
        jPanel_Memoria.add(jLabel_Linea2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 40, 70, 10));

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Dirección máxima._1.png"))); // NOI18N
        jPanel_Memoria.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 280, 60, 50));

        jLabel2.setBackground(new java.awt.Color(70, 70, 70));
        jLabel2.setFont(new java.awt.Font("Open Sans", 1, 13)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(112, 112, 112));
        jLabel2.setText("0");
        jPanel_Memoria.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 10, -1, -1));

        jPanel_Neumann.add(jPanel_Memoria, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 280, 370, 320));

        jPanel_Unidad_Ejecucion.setBackground(new java.awt.Color(0, 51, 51));
        jPanel_Unidad_Ejecucion.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel_ALU.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/ALU.png"))); // NOI18N
        jPanel_Unidad_Ejecucion.add(jLabel_ALU, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 160, 210, 80));

        jLabel_Registros.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Registros.png"))); // NOI18N
        jPanel_Unidad_Ejecucion.add(jLabel_Registros, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 40, 290, 70));

        jLabel_RegistroE.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Registro de Estatus.png"))); // NOI18N
        jPanel_Unidad_Ejecucion.add(jLabel_RegistroE, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 290, 210, 90));

        jLabel_FlechaA.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Fecha.png"))); // NOI18N
        jPanel_Unidad_Ejecucion.add(jLabel_FlechaA, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 100, 20, 70));

        jLabel_FlechaArri.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Fecha 2.png"))); // NOI18N
        jPanel_Unidad_Ejecucion.add(jLabel_FlechaArri, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 110, 20, 60));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Fecha.png"))); // NOI18N
        jPanel_Unidad_Ejecucion.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 230, 20, 60));

        jPanel_Neumann.add(jPanel_Unidad_Ejecucion, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 190, 340, 410));

        jPanel_UnidadC.setBackground(new java.awt.Color(0, 51, 51));
        jPanel_UnidadC.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel_Neumann.add(jPanel_UnidadC, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 240, 360, 360));

        jPanel1.setBackground(new java.awt.Color(0, 51, 51));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 60, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );

        jPanel_Neumann.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1210, 200, 60, 400));

        jLabel_Memoria.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/MEMORIA.png"))); // NOI18N
        jPanel_Neumann.add(jLabel_Memoria, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 600, 90, 30));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Flecha 6.png"))); // NOI18N
        jPanel_Neumann.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 730, 1030, 10));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Flecha 7.png"))); // NOI18N
        jPanel_Neumann.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 590, 20, 150));

        jLabel_UnidadEje.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/UNIDAD DEEJECUCION.png"))); // NOI18N
        jPanel_Neumann.add(jLabel_UnidadEje, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 600, 100, 40));

        getContentPane().add(jPanel_Neumann, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1366, 868));

        setSize(new java.awt.Dimension(1366, 829));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Neumann_Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Neumann_Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Neumann_Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Neumann_Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Neumann_Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Flecha_Grande;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel_ALU;
    private javax.swing.JLabel jLabel_CuadroDirec;
    private javax.swing.JLabel jLabel_Decod;
    private javax.swing.JLabel jLabel_Flecha4;
    private javax.swing.JLabel jLabel_FlechaA;
    private javax.swing.JLabel jLabel_FlechaAD;
    private javax.swing.JLabel jLabel_FlechaArri;
    private javax.swing.JLabel jLabel_Linea1;
    private javax.swing.JLabel jLabel_Linea2;
    private javax.swing.JLabel jLabel_Memoria;
    private javax.swing.JLabel jLabel_RegistroE;
    private javax.swing.JLabel jLabel_Registros;
    private javax.swing.JLabel jLabel_UnidadEje;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel_Memoria;
    private javax.swing.JPanel jPanel_Neumann;
    private javax.swing.JPanel jPanel_UnidadC;
    private javax.swing.JPanel jPanel_Unidad_Ejecucion;
    // End of variables declaration//GEN-END:variables
}
